#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

# Not .env: nothing here is read at runtime. Unity bakes the project id into
# ProjectSettings.asset when you link. This file is only a record so re-runs can
# offer your previous answers back.
ENV_FILE=".env.ugs"

banner "Oiled Up — Unity Gaming Services setup"

say "Co-op needs four UGS services switched on for this project:"
note "  Authentication — gives each player a stable id, which is what makes rejoin work"
note "  Relay          — relays traffic so nobody has to port-forward"
note "  Lobby          — join codes, so your friend can find your game"
note "  Vivox          — proximity voice"
printf '\n'
note "You drive the browser and the Unity Editor. Nothing here is secret: a UGS"
note "project id ships inside the game build anyway."
pause "Ready?"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Unity Cloud: pick or create the project"
say "First we need a cloud project for Oiled Up to attach to."
open_url "https://cloud.unity.com/home/organizations"
step "Sign in with the same Unity account the Editor uses."
step "Pick your organisation, or create one if this is your first project."
step "Open Projects, then either create a project called 'Oiled Up' or open the existing one."
step "With the project open, find its Project ID — it is a UUID, usually shown"
step "  under the project name or in the URL after /projects/."
ask UGS_PROJECT_ID "Paste the Project ID:"
write_env UGS_PROJECT_ID "$UGS_PROJECT_ID"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Unity Editor: link the project"
say "Now point the Editor at it. This is what writes cloudProjectId into"
say "ProjectSettings.asset, which every service reads."
warn "Do this in the Unity Editor, not the browser."
step "Edit → Project Settings → Services."
step "Sign in if prompted, then choose your organisation."
step "Select the project you just opened and click Link."
note "If it offers to create a new project instead, cancel and pick the existing"
note "one — two projects with the same name gets confusing fast."
pause "Linked? Press Enter."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Enable Authentication"
say "Authentication issues each player a PlayerId that survives a disconnect."
say "That id is the key the host uses to give you your session back on rejoin,"
say "so without this, rejoin cannot work at all."
open_url "https://cloud.unity.com/home/organizations"
step "In your project, open Player Authentication (under Services or Products)."
step "Click Get started / Enable if it is not already on."
step "Open Sign-in methods and make sure Anonymous is enabled."
note "Anonymous is all we need — nobody should have to make an account to play."
pause "Authentication on, anonymous enabled?"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Enable Relay"
say "Relay carries traffic between host and clients, so neither of you has to"
say "open a port on your router."
open_url "https://cloud.unity.com/home/organizations"
step "In your project, open Relay."
step "Click Get started / Enable."
note "The free tier is generous and four players is nowhere near it."
pause "Relay enabled?"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Enable Lobby"
say "Lobby is how a join code turns into a Relay connection."
open_url "https://cloud.unity.com/home/organizations"
step "In your project, open Lobby."
step "Click Get started / Enable."
pause "Lobby enabled?"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Enable Vivox"
say "Vivox does proximity voice — hearing someone at the far bench get quieter"
say "is a lot of what makes a shared lab feel like one."
open_url "https://cloud.unity.com/home/organizations"
step "In your project, open Vivox."
step "Click Get started / Enable and accept the terms."
step "Back in the Editor: Project Settings → Services → Vivox, and confirm the"
step "  credentials have populated. They should fill in automatically once enabled."
note "Voice is the last thing wired up, so it is fine if this one lags behind."
pause "Vivox enabled?"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Verify the link"
say "Checking that the Editor actually wrote the project id to disk."
SETTINGS="ProjectSettings/ProjectSettings.asset"

if [[ ! -f "$SETTINGS" ]]; then
  warn "Cannot find $SETTINGS — run this from the project root."
  SKIPPED+=("verification: run setup-ugs.sh from the project root")
else
  FOUND=$(grep -E "^  cloudProjectId: " "$SETTINGS" | sed "s/^  cloudProjectId: //" | tr -d " ")
  if [[ -z "$FOUND" ]]; then
    warn "cloudProjectId is still empty. The link did not take."
    note "Go back to stage 2: Edit → Project Settings → Services, and link again."
    note "Unity sometimes needs the Editor restarted before it writes this."
    SKIPPED+=("linking the Editor to the cloud project (cloudProjectId is empty)")
  else
    printf "  %s✓%s cloudProjectId is set: %s\n" "$GREEN" "$RESET" "$FOUND"
    if [[ -n "$UGS_PROJECT_ID" && "$FOUND" != "$UGS_PROJECT_ID" ]]; then
      warn "That does not match the id you pasted in stage 1:"
      note "  pasted: $UGS_PROJECT_ID"
      note "  linked: $FOUND"
      note "The Editor is linked to a different project than you think."
      SKIPPED+=("check which project the Editor is linked to — the ids disagree")
    fi
  fi
fi

printf "\n"
say "Commit ProjectSettings.asset once this is green — the linked id belongs in"
say "the repo so your friend's checkout points at the same project."

finish
