using System;
using Residue.Gameplay.UI;
using UnityEngine.UIElements;

namespace Residue.Net.UI
{
    /// <summary>
    /// The credits screen (#53), off the main menu (#42): the people who made the game, and the
    /// third-party section CC-BY and several of the other permissive licences this project uses
    /// actually require in the shipped product — a licence recorded only in
    /// <c>Assets/Art/Imported/CREDITS.md</c> satisfies nobody reading it from inside the build.
    /// <para>
    /// <b>Nothing here is transcribed.</b> Both long sections are <see cref="CreditsContent"/>,
    /// generated by <c>Residue/Content/Rebuild Credits</c> from CREDITS.md and from every resolved
    /// package's own notice file — see <c>Residue.Editor.Content.CreditsBuilder</c>. A hand-typed
    /// second copy of either is exactly the copy that quietly stops matching what shipped. The "made
    /// by" line is the one thing on this screen that is not licence text, so it is the one line
    /// written by hand.
    /// </para>
    /// <para>
    /// A plain class rather than a MonoBehaviour, built once, following every other page of this
    /// shell — see <c>SettingsPanel</c> for the reasoning. There is nothing on it that changes after
    /// construction, so unlike its siblings it has no meaningful <c>Refresh</c>.
    /// </para>
    /// </summary>
    public sealed class CreditsPanel
    {
        private const float PanelWidth = 620f;
        private const float SectionMaxHeight = 260f;

        public CreditsPanel(Action back)
        {
            Root = UiKit.Panel(PanelWidth);

            var column = UiKit.Column(UiKit.GapWide);
            Root.Add(column);

            column.Add(UiKit.Heading("CREDITS"));
            column.Add(UiKit.Body("OILED UP is made by Emmanuel Lampe and Kevin-Timo Salmen."));

            column.Add(UiKit.Divider());

            column.Add(UiKit.Body("Third-party art"));
            column.Add(UiKit.Hint(
                "Recorded in Assets/Art/Imported/CREDITS.md and reproduced here verbatim, because " +
                "some of these licences require attribution in the game itself rather than only in " +
                "the repository."));
            column.Add(Section(CreditsContent.ThirdPartyArt));

            column.Add(UiKit.Divider());

            column.Add(UiKit.Body("Third-party software"));
            column.Add(UiKit.Hint(
                "Licence notices shipped inside the Unity packages this build is made from."));
            column.Add(PackageNoticesSection());

            column.Add(UiKit.Divider());

            var footer = UiKit.Row();
            footer.Add(UiKit.Spacer());
            footer.Add(UiKit.QuietButton("BACK", () => back?.Invoke()));
            column.Add(footer);
        }

        /// <summary>The tree to parent. Built once; there is nothing on it to refresh.</summary>
        public VisualElement Root { get; }

        /// <summary>
        /// One scrolling label reproducing <see cref="CreditsContent.ThirdPartyArt"/>. A single
        /// <see cref="Label"/> is fine here — CREDITS.md is short by construction, since an art asset
        /// earns an entry only when one is actually sourced.
        /// </summary>
        private static VisualElement Section(string text)
        {
            var scroller = new ScrollView(ScrollViewMode.Vertical);
            scroller.style.maxHeight = SectionMaxHeight;
            scroller.style.flexShrink = 1f;
            scroller.Add(UiKit.Body(text));
            return scroller;
        }

        /// <summary>
        /// One label per package rather than one label holding every notice concatenated: the
        /// combined text is on the order of hundreds of kilobytes across a couple of dozen packages,
        /// and word-wrapping that as a single element is the kind of thing that is fine in a short
        /// test and a stutter on the actual screen. Splitting on
        /// <see cref="CreditsContent.PackageNoticeSeparator"/> costs nothing extra to compute — it is
        /// the exact string <c>CreditsBuilder</c> joined the notices with, not a second guess at it.
        /// </summary>
        private static VisualElement PackageNoticesSection()
        {
            var scroller = new ScrollView(ScrollViewMode.Vertical);
            scroller.style.maxHeight = SectionMaxHeight;
            scroller.style.flexShrink = 1f;

            var list = UiKit.Column();
            string[] notices = CreditsContent.PackageNotices.Split(
                new[] { CreditsContent.PackageNoticeSeparator }, StringSplitOptions.None);

            foreach (string notice in notices)
            {
                if (string.IsNullOrWhiteSpace(notice)) continue;
                list.Add(UiKit.Body(notice));
            }

            scroller.Add(list);
            return scroller;
        }
    }
}
