using System.Collections.Generic;
using UnityEngine;

namespace Residue.Data
{
    /// <summary>
    /// Every definition in the project, in one asset.
    /// <para>
    /// Generated by <c>Residue > Content > Rebuild Definitions</c> alongside the definitions
    /// themselves. It exists so runtime code takes a single serialized reference instead of calling
    /// <c>Resources.LoadAll</c> — which would silently pick up anything anyone dropped in the folder
    /// and give no compile-time signal when content is missing.
    /// </para>
    /// </summary>
    [CreateAssetMenu(menuName = "Residue/Content Catalog", fileName = "ContentCatalog")]
    public sealed class ContentCatalog : ScriptableObject
    {
        [SerializeField] private List<ElementDef> elements = new();
        [SerializeField] private List<RootCauseDef> causes = new();
        [SerializeField] private List<EquipmentProfileDef> profiles = new();
        [SerializeField] private List<FaultDef> faults = new();
        [SerializeField] private List<MachineDef> machines = new();

        public IReadOnlyList<ElementDef> Elements => elements;
        public IReadOnlyList<RootCauseDef> Causes => causes;
        public IReadOnlyList<EquipmentProfileDef> Profiles => profiles;
        public IReadOnlyList<FaultDef> Faults => faults;
        public IReadOnlyList<MachineDef> Machines => machines;

        public ElementDef Element(string id) => Find(elements, id);
        public RootCauseDef Cause(string id) => Find(causes, id);
        public EquipmentProfileDef Profile(string id) => Find(profiles, id);
        public FaultDef Fault(string id) => Find(faults, id);
        public MachineDef Machine(string id) => Find(machines, id);

        private static ElementDef Find(List<ElementDef> list, string id)
        {
            foreach (var e in list)
            {
                if (e != null && e.Id == id) return e;
            }
            return null;
        }

        private static RootCauseDef Find(List<RootCauseDef> list, string id)
        {
            foreach (var e in list)
            {
                if (e != null && e.Id == id) return e;
            }
            return null;
        }

        private static EquipmentProfileDef Find(List<EquipmentProfileDef> list, string id)
        {
            foreach (var e in list)
            {
                if (e != null && e.Id == id) return e;
            }
            return null;
        }

        private static FaultDef Find(List<FaultDef> list, string id)
        {
            foreach (var e in list)
            {
                if (e != null && e.Id == id) return e;
            }
            return null;
        }

        private static MachineDef Find(List<MachineDef> list, string id)
        {
            foreach (var e in list)
            {
                if (e != null && e.Id == id) return e;
            }
            return null;
        }

        public bool IsComplete =>
            elements.Count > 0 && profiles.Count > 0 && faults.Count > 0 && machines.Count > 0;
    }
}
