using System;
using System.Collections.Generic;
using UnityEngine;

namespace Residue.Data
{
    /// <summary>
    /// How one fault moves one element away from its healthy baseline.
    /// Applied as: <c>value = baseline * lerp(1, multiplier, p) + flatAdd * p</c>
    /// where <c>p = ProgressionOverSeverity.Evaluate(severity01)</c>.
    /// </summary>
    [Serializable]
    public sealed class ElementDelta
    {
        [SerializeField] private ElementDef element;

        [Tooltip("Scales the healthy baseline at full progression. 3 = triple the normal reading.")]
        [SerializeField] private float multiplier = 1f;

        [Tooltip("Added on top, in the element's own unit. Use for elements whose healthy baseline is ~0.")]
        [SerializeField] private float flatAdd;

        [Tooltip("Maps sample severity (0..1) to how far the fault has progressed. " +
                 "Linear 0->1 is a fine default; an ease-in curve makes early-stage faults subtler.")]
        [SerializeField] private AnimationCurve progressionOverSeverity = AnimationCurve.Linear(0f, 0f, 1f, 1f);

        public ElementDef Element => element;
        public float Multiplier => multiplier;
        public float FlatAdd => flatAdd;
        public AnimationCurve ProgressionOverSeverity => progressionOverSeverity;

        /// <summary>Apply this delta to a healthy baseline value at the given severity (0..1).</summary>
        public float Apply(float baseline, float severity01)
        {
            float p = progressionOverSeverity?.Evaluate(Mathf.Clamp01(severity01)) ?? Mathf.Clamp01(severity01);
            return baseline * Mathf.LerpUnclamped(1f, multiplier, p) + flatAdd * p;
        }
    }

    /// <summary>
    /// A diagnosable condition. Content core (§4.3): a sample is generated by picking a fault
    /// (or none), applying its signature to the profile baselines, then adding noise.
    /// </summary>
    [CreateAssetMenu(menuName = "Residue/Fault", fileName = "Fault_")]
    public sealed class FaultDef : ScriptableObject
    {
        [SerializeField] private string id;

        [Tooltip("Shown to the player only AFTER the verdict resolves. Never leak it in the results UI.")]
        [SerializeField] private string displayName;

        [SerializeField] private FaultSeverity severity = FaultSeverity.Developing;
        [SerializeField] private List<ElementDelta> signature = new();

        [Tooltip("Cascade (§4.3): dirt ingress causes abrasive wear. Generator may add these as secondary faults.")]
        [SerializeField] private List<FaultDef> canCause = new();

        [Tooltip("Equipment profiles this fault can occur on. Empty = any.")]
        [SerializeField] private List<EquipmentProfileDef> validOn = new();

        [Tooltip("Days until the equipment fails if the player does not file CRITICAL.")]
        [SerializeField] private int daysToFailure = 5;

        [SerializeField] private float repairCost;

        [Tooltip("Cost of filing CRITICAL when this fault is NOT present.")]
        [SerializeField] private float teardownCostIfWrong;

        [Tooltip("The answer to the root-cause bonus (§5.4). For cleaner carryover this is the WASHER " +
                 "LINE, not the tank showing the symptom. Leave empty if the fault has no distinct cause.")]
        [SerializeField] private RootCauseDef rootCause;

        [Tooltip("What actually happens when this is passed as NORMAL. Shown in the incident report.\n\n" +
                 "Lives on the fault rather than in the resolver so that adding a fault with a new " +
                 "kind of consequence needs no code, and so the worst outcome in the game is a data " +
                 "value someone can find rather than a branch someone has to remember exists.")]
        [SerializeField, TextArea(2, 4)] private string missedConsequence;

        public string Id => id;
        public string DisplayName => string.IsNullOrEmpty(displayName) ? id : displayName;
        public FaultSeverity Severity => severity;
        public IReadOnlyList<ElementDelta> Signature => signature;
        public IReadOnlyList<FaultDef> CanCause => canCause;
        public IReadOnlyList<EquipmentProfileDef> ValidOn => validOn;
        public int DaysToFailure => daysToFailure;
        public float RepairCost => repairCost;
        public float TeardownCostIfWrong => teardownCostIfWrong;
        public RootCauseDef RootCause => rootCause;

        /// <summary>What happens when this fault is passed as NORMAL. Never shown before resolution.</summary>
        public string MissedConsequence => string.IsNullOrEmpty(missedConsequence)
            ? "The tank was left in service and the customer's parts were affected."
            : missedConsequence;

        public bool IsValidOn(EquipmentProfileDef profile)
            => validOn == null || validOn.Count == 0 || validOn.Contains(profile);

        public override string ToString() => $"Fault:{Id}";
    }
}
